Repository NOW-SOPT-CDSP-WEB6/Naver-Reservation-FE, pull requests merged in 2024-05, with the labels that each got.

#2 [Init] 초기세팅을 진행하고 개발환경을 구축한다.
  .babelrc
  .eslintrc.cjs
  .prettierrc
  package.json
  src/App.css
  src/App.tsx
  src/api/date.ts
  src/assets/svgs/react.svg
  src/components/domainEx/Ex.tsx
  src/constants/index.ts
  src/hooks/common/useOverlay.ts
  src/index.css
  src/main.tsx
  src/pages/Test/Test.tsx
  src/router/router.tsx
  src/styles/GlobalStyle.ts
  src/styles/fonts.css
  src/styles/theme.ts
  src/type/date.ts
  src/utils/date.ts
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: documentation

#6 [Feat] 라우터를 설계하고, 애플리케이션에 필요한 레이아웃 컴포넌트를 개발한다.
  index.html
  package.json
  src/App.tsx
  src/assets/svgs/home/home_btn_write.svg
  src/assets/svgs/home/home_ic_all.svg
  src/assets/svgs/home/home_ic_all_white.svg
  src/assets/svgs/home/home_ic_back.svg
  src/assets/svgs/home/home_ic_beauty.svg
  src/assets/svgs/home/home_ic_beauty_white.svg
  src/assets/svgs/home/home_ic_bell.svg
  src/assets/svgs/home/home_ic_calendar.svg
  src/assets/svgs/home/home_ic_day.svg
  src/assets/svgs/home/home_ic_edit.svg
  src/assets/svgs/home/home_ic_globe.svg
  src/assets/svgs/home/home_ic_health.svg
  src/assets/svgs/home/home_ic_health_white.svg
  src/assets/svgs/home/home_ic_home.svg
  src/assets/svgs/home/home_ic_left.svg
  src/assets/svgs/home/home_ic_life.svg
  src/assets/svgs/home/home_ic_life_white.svg
  src/assets/svgs/home/home_ic_living.svg
  src/assets/svgs/home/home_ic_living_white.svg
  src/assets/svgs/home/home_ic_restaurant.svg
  src/assets/svgs/home/home_ic_restaurant_white.svg
  src/assets/svgs/home/home_ic_robot.svg
  src/assets/svgs/home/home_ic_sport.svg
  src/assets/svgs/home/home_ic_sport_white.svg
  src/assets/svgs/home/home_ic_star_off.svg
  src/assets/svgs/home/home_ic_star_on.svg
  src/assets/svgs/home/home_ic_ticket.svg
  src/assets/svgs/home/home_ic_ticket_white.svg
  src/assets/svgs/react.svg
  src/assets/svgs/status-group.svg
  src/assets/svgs/time.svg
  src/components/@common/Text/Text.style.ts
  src/components/@common/Text/Text.tsx
  src/components/layout/header/Header.style.ts
  src/components/layout/header/Header.tsx
  src/components/layout/mobileLayout/MobileLayout.style.ts
  src/components/layout/mobileLayout/MobileLayout.tsx
  src/main.tsx
  src/pages/Test/Test.tsx
  src/pages/donePage/DonePage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/reviewPage/ReviewPage.tsx
  src/router/router.tsx
  yarn.lock
Labels: ✨Feature, ⚙️Setting

#4 [Feat] 버튼 컴포넌트를 개발한다.
  src/components/@common/BottomNavBtn/BottomNavBtn.style.ts
  src/components/@common/BottomNavBtn/BottomNavBtn.tsx
  src/components/@common/Button/Button.style.ts
  src/components/@common/Button/Button.tsx
Labels: ✨Feature

#9 [refactor] theme color 변수 재명명
  src/components/@common/Button/Button.style.ts
  src/components/layout/mobileLayout/MobileLayout.style.ts
  src/styles/theme.ts
Labels: 🔨Refactor

#14 [Feat] Content Box 컴포넌트를 개발한다.
  src/App.tsx
  src/components/@common/Button/Button.style.ts
  src/components/@common/ContentBox/ContentBox.style.ts
  src/components/@common/ContentBox/ContentBox.tsx
Labels: ✨Feature

#16 [Feat] title 컴포넌트 및 스타일 생성
  src/components/@common/Title/Title.style.ts
  src/components/@common/Title/Title.tsx
Labels: ✨Feature

#21 [Refactor] 레이아웃 컴포넌트의 스타일을 수정하고, 기타 불필요 코드 혹은 에러 코드를 수정한다.
  src/App.tsx
  src/components/@common/Button/Button.style.ts
  src/components/layout/header/Header.style.ts
  src/components/layout/mobileLayout/MobileLayout.style.ts
  src/styles/GlobalStyle.ts
  svg.d.ts
Labels: 🔨Refactor

#22 [Feat] 홈 상단 페이지에 사용되는 컴포넌트들을 구현한다.
  src/components/home/common/homeCategoryBtn/HomeCategoryBtn.style.ts
  src/components/home/common/homeCategoryBtn/HomeCategoryBtn.tsx
  src/components/home/common/homeMenu/HomeMenu.style.ts
  src/components/home/common/homeMenu/HomeMenu.tsx
  src/components/home/common/homeMenu/HomeMenuItem.tsx
  src/components/home/common/homeMyInfo/HomeMyInfo.style.ts
  src/components/home/common/homeMyInfo/HomeMyInfo.tsx
  src/components/home/common/homeMyPlaceBtn/HomeMyPlaceBtn.tsx
  src/components/home/common/homeNotice/HomeNotice.style.ts
  src/components/home/common/homeNotice/HomeNotice.tsx
  src/components/home/common/homeTopBar/HomeTopBar.tsx
  src/constants/index.ts
  src/utils/category.ts
  src/utils/date.ts
Labels: ✨Feature

#20 [Feat] review 페이지 Drag&Drop 컴포넌트를 구현한다.
  src/assets/svgs/review/review_btn_plus.svg
  src/components/@common/ContentBox/ContentBox.style.ts
  src/components/@common/ContentBox/ContentBox.tsx
  src/pages/reviewPage/DragDrop/DragDrop.style.ts
  src/pages/reviewPage/DragDrop/DragDrop.tsx
  src/pages/reviewPage/Header/Header.style.ts
  src/pages/reviewPage/ReviewPage.tsx
Labels: ✨Feature

#25 [Feat] 홈 페이지 하단에 쓰일 컴포넌트들을 구현한다.
  src/assets/svgs/home/home_ic_down.svg
  src/assets/svgs/home/home_ic_right.svg
  src/assets/svgs/home/home_ic_up.svg
  src/components/domainEx/Ex.tsx
  src/components/home/common/homeCategoryChip/HomeCategoryChip.style.ts
  src/components/home/common/homeCategoryChip/HomeCategoryChip.tsx
  src/components/home/common/homeCategoryChip/HomeCategoryChips.tsx
  src/components/home/common/homeFooter/HomeFooter.style.ts
  src/components/home/common/homeFooter/HomeFooter.tsx
  src/components/home/common/homeMostReservation/HomeMostReservation.style.ts
  src/components/home/common/homeMostReservation/HomeMostReservation.tsx
  src/components/home/common/homeMostReservation/HomeMostReservationItem.tsx
  src/components/home/common/homeMyInfo/HomeMyInfo.tsx
  src/components/home/common/homeReservationCard/HomeReservationCard.style.ts
  src/components/home/common/homeReservationCard/HomeReservationCardDetail.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardDetailContent.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardHeader.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardItem.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardList.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardReview.tsx
  src/type/date.ts
Labels: ✨Feature

#28 [Feat] review 페이지 bottom 구현한다.
  src/assets/svgs/home_ic_back.svg
  src/assets/svgs/review/Vector_8.svg
  src/components/@common/BottomNavBtn/BottomNavBtn.style.ts
  src/components/@common/BottomNavBtn/BottomNavBtn.tsx
  src/components/@common/Button/Button.style.ts
  src/pages/reviewPage/Bottom/Bottom.style.ts
  src/pages/reviewPage/Bottom/Bottom.tsx
  src/pages/reviewPage/ReviewPage.tsx
  src/pages/reviewPage/ReviewWriting/ReviewWriting.style.ts
  src/pages/reviewPage/ReviewWriting/ReviewWriting.tsx
Labels: ✨Feature

#33 [Feat] done 상단 페이지의 컴포넌트를 구현하고 스타일을 생성한다.
  src/App.tsx
  src/assets/svgs/done/done_ic_exit.svg
  src/assets/svgs/done/done_ic_star_red.svg
  src/assets/svgs/done/prof_img.svg
  src/assets/svgs/done/review_img.svg
  src/pages/donePage/DoneHeader/DoneHeader.style.ts
  src/pages/donePage/DoneHeader/DoneHeader.tsx
  src/pages/donePage/DonePage.tsx
  src/pages/donePage/ReviewBox/ReviewBox.style.ts
  src/pages/donePage/ReviewBox/ReviewBox.tsx
  src/pages/donePage/ReviewContents/ReviewContents.style.ts
  src/pages/donePage/ReviewContents/ReviewContents.tsx
  src/pages/donePage/TopBar/TopBar.style.ts
  src/pages/donePage/TopBar/TopBar.tsx
Labels: ✨Feature

#38 [Feat] keyword 페이지에 필요한 Carousel 컴포넌트를 구현한다.
  src/assets/svgs/LikeOff.svg
  src/assets/svgs/LikeOn.svg
  src/assets/svgs/keyword/keyword_btn_detail_click.svg
  src/assets/svgs/keyword/keyword_btn_detail_defalt.svg
  src/constants/badge.ts
  src/constants/index.ts
  src/pages/keywordPage/Badge/Badge.style.ts
  src/pages/keywordPage/Badge/Badge.tsx
  src/pages/keywordPage/Carousel/Carousel.style.ts
  src/pages/keywordPage/Carousel/Carousel.tsx
  src/pages/keywordPage/CarouselCard/CarouselCard.style.ts
  src/pages/keywordPage/CarouselCard/CarouselCard.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/keywordPage/LikeBox/LikeBox.style.ts
  src/pages/keywordPage/LikeBox/LikeBox.tsx
  src/styles/theme.ts
Labels: ✨Feature

#46 [Feat] 홈 페이지의 get, post API를 생성하고 query, mutation을 통해 송수신을 관리하도록 하였습니다.
  .github/workflows/frontend-deploy-every-push.yml
  package.json
  src/api/axiosInstance.ts
  src/api/getAllReservation.ts
  src/api/index.ts
  src/components/home/common/homeReservationCard/HomeReservationCard.style.ts
  src/components/home/common/homeReservationCard/HomeReservationCardItem.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardList.tsx
  src/components/home/homeReservationDetail/HomeReservationDetail.tsx
  src/constants/api.ts
  src/constants/index.ts
  src/hooks/common/useFunnel.tsx
  src/hooks/home/useAllReservation.ts
  src/hooks/reservation/useReservationInfoQuery.ts
  src/hooks/reservation/useReservationMarkMutation.ts
  src/hooks/reservation/useReservationQuery.ts
  src/main.tsx
  src/pages/ReviewFunnelPage/ReviewFunnelPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/keywordPage/Header/Header.tsx
  src/type/reservation.ts
  src/vite-env.d.ts
  tsconfig.json
  yarn.lock
Labels: ✨Feature

#53 [Feat] Funnel 구조 삭제(url parameter가 꼭 필요하므로 라우트 이동 필요) + build 에러를 확인 및 수정한다.
  src/hooks/common/useFunnel.tsx
  src/hooks/query/useReservationMarkMutation.ts
  src/hooks/query/useReservationQuery.ts
  src/pages/ReviewFunnelPage/ReviewFunnelPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/keywordPage/KeywordPage.tsx
  tsconfig.json
Labels: 🔨Refactor, ✈️Deployment

#56 [Feat] 홈페이지에서 리뷰쓰기를 클릭하였을 때 해당 데이터를 navigate의 state로 넘기고, 각 페이지에선 useLocation을 통해 받았습니다.
  src/components/home/common/homeReservationCard/HomeReservationCardItem.tsx
  src/components/home/common/homeReservationCard/HomeReservationCardReview.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/reviewPage/ReviewPage.tsx
Labels: ✨Feature

#58 [Feat] Stepper 를 구현하고 각 페이지에 연결한다.
  src/assets/svgs/stepper/doneOff.svg
  src/assets/svgs/stepper/doneOn.svg
  src/assets/svgs/stepper/keyword.svg
  src/assets/svgs/stepper/reviewOff.svg
  src/assets/svgs/stepper/reviewOn.svg
  src/components/@common/Stepper/Stepper.style.ts
  src/components/@common/Stepper/Stepper.tsx
  src/main.tsx
  src/pages/donePage/DonePage.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/reviewPage/Header/Header.tsx
  src/pages/reviewPage/ReviewPage.tsx
Labels: ✨Feature

#61 [Feat] navigate 연결, 이미지 파일 수정, 버튼 밑에 padding값 수정
  src/assets/img/done_img_1.png
  src/assets/img/done_img_2.png
  src/assets/img/prof_img_1.png
  src/assets/img/review.png
  src/pages/donePage/Place/Place.style.ts
  src/pages/donePage/Place/Place.tsx
  src/pages/donePage/ReviewBox/MoreReviewBox.style.ts
  src/pages/donePage/ReviewBox/MoreReviewBox.tsx
  src/pages/donePage/ReviewBox/ReviewBox.style.ts
  src/pages/donePage/ReviewBox/ReviewBox.tsx
  src/pages/donePage/ReviewContents/ReviewContents.tsx
  src/pages/donePage/TopBar/TopBar.style.ts
  src/pages/donePage/TopBar/TopBar.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/reviewPage/ReviewPage.tsx
Labels: ✨Feature

#64 [Refactor] index.html 및 workflows 파일 수정
  .github/workflows/frontend-deploy-every-push.yml
  index.html
  public/favicon.svg
  src/hooks/query/useReviewWritingMutation.ts
Labels: 📄Documentation, 🔨Refactor

#66 [Refactor] favicon 수정
  index.html
Labels: 🔨Refactor

#65 [Fix] DoneBtn, reviewDate 수정
  src/assets/img/bread.png
  src/pages/donePage/Place/Place.style.ts
  src/pages/donePage/ReviewBox/MoreReviewBox.tsx
  src/pages/donePage/ReviewBox/ReviewBox.tsx
Labels: 🐛Bug, ✨Feature

#68 [Refactor] reservation card label prop 대체 텍스트로 사용
  src/pages/homePage/HomePage.tsx
Labels: 🔨Refactor
